apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ze5lrd1o7-go
  janus-idp.io/tekton: ze5lrd1o7-go
  backstage.io/kubernetes-id: ze5lrd1o7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ze5lrd1o7-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
